using ApplicationServiceLayerTraining.ApplicationService.Contracts.ServiceFrameworks;
using ApplicationServiceLayerTraining.ApplicationService.Dtos.PersonDtos;

namespace ApplicationServiceLayerTraining.ApplicationService.Contracts;

public interface IPersonService : IService<ServiceCreatePersonDto, ServiceSelectPersonDto, ServiceSelectAllPeopleDto, ServiceUpdatePersonDto, ServiceDeletePersonDto>
{
}