using ApplicationServiceLayerTraining.ApplicationService.Contracts.ServiceFrameworks;
using ApplicationServiceLayerTraining.ApplicationService.Dtos.ProductDtos;
using ApplicationServiceLayerTraining.Frameworks.Contracts;

namespace ApplicationServiceLayerTraining.ApplicationService.Contracts;

public interface IProductService : IService<ServiceCreateProductDto, ServiceSelectProductDto, ServiceSelectAllProductsDto, ServiceUpdateProductDto, ServiceDeleteProductDto>
{
}
